services:
  app:
    build: !reset
    image: ${DOCKER_APP_IMAGE}
    environment: !override
      - SKIP_SFTP=skip_sftp
    volumes: !override
      - artifacts:/opt/app/artifacts
    secrets: !reset

volumes:
  artifacts:

secrets: !reset
